const API_BASE_URL = "http://127.0.0.1:5000";
const fileInput=document.getElementById("fileInput"),dropZone=document.getElementById("dropZone"),previewImg=document.getElementById("previewImg"),overlayCanvas=document.getElementById("overlayCanvas"),imageWrapper=document.getElementById("imageWrapper"),dropPrompt=document.querySelector(".drop-zone__prompt"),recognizeBtn=document.getElementById("recognizeBtn"),resetBtn=document.getElementById("resetBtn"),resultsCard=document.getElementById("resultsCard"),loadingState=document.getElementById("loadingState"),resultsContent=document.getElementById("resultsContent"),recognizedTextEl=document.getElementById("recognizedText"),confidenceTextEl=document.getElementById("confidenceText"),confidenceFillEl=document.getElementById("confidenceFill"),lineGridEl=document.getElementById("lineGrid"),errorTextEl=document.getElementById("errorText"),copyBtn=document.getElementById("copyBtn");
let selectedFile=null;
dropZone.addEventListener("click",e=>{if(!e.target.closest("button"))fileInput.click()});
fileInput.addEventListener("change",e=>{if(e.target.files.length)handleFile(e.target.files[0])});
["dragenter","dragover"].forEach(t=>dropZone.addEventListener(t,e=>{e.preventDefault();dropZone.classList.add("drop-zone--active")}));
["dragleave","drop"].forEach(t=>dropZone.addEventListener(t,e=>{e.preventDefault();dropZone.classList.remove("drop-zone--active")}));
dropZone.addEventListener("drop",e=>{const f=e.dataTransfer.files[0];if(f)handleFile(f)});
function handleFile(file){if(!file.type.startsWith("image/")){alert("Please upload an image file.");return}selectedFile=file;const r=new FileReader();r.onload=e=>{previewImg.src=e.target.result;previewImg.onload=()=>{clearOverlayCanvas();imageWrapper.hidden=false;dropPrompt.hidden=true}};r.readAsDataURL(file);recognizeBtn.disabled=false;resetBtn.hidden=false;resultsCard.hidden=true}
function clearOverlayCanvas(){const c=overlayCanvas.getContext("2d");overlayCanvas.width=previewImg.naturalWidth||1;overlayCanvas.height=previewImg.naturalHeight||1;c.clearRect(0,0,overlayCanvas.width,overlayCanvas.height)}
function drawBoundingBoxes(lines){const c=overlayCanvas.getContext("2d"),w=previewImg.naturalWidth,h=previewImg.naturalHeight;overlayCanvas.width=w;overlayCanvas.height=h;c.clearRect(0,0,w,h);lines.forEach((line,i)=>{const [x,y,bw,bh]=line.box||[];if(!bw)return;c.lineWidth=Math.max(2,Math.round(h/250));c.strokeStyle="#10b981";c.strokeRect(x,y,bw,bh);c.fillStyle="#10b981";const fs=Math.max(12,Math.round(h/35));c.font=`600 ${fs}px sans-serif`;const label=`Line ${i+1}`;const tw=c.measureText(label).width;c.fillRect(x,Math.max(0,y-fs-6),tw+10,fs+6);c.fillStyle="#fff";c.fillText(label,x+5,Math.max(fs,y-5))})}
recognizeBtn.addEventListener("click",async()=>{if(!selectedFile)return;resultsCard.hidden=false;loadingState.hidden=false;resultsContent.hidden=true;errorTextEl.hidden=true;copyBtn.hidden=true;recognizeBtn.disabled=true;const fd=new FormData();fd.append("image",selectedFile);try{const r=await fetch(`${API_BASE_URL}/api/recognize`,{method:"POST",body:fd});const data=await r.json().catch(()=>({}));if(!r.ok||data.success===false)throw new Error(data.error||`Request failed (${r.status})`);loadingState.hidden=true;resultsContent.hidden=false;recognizedTextEl.textContent=data.text||"";const pct=Math.round((data.confidence||0)*100);confidenceTextEl.textContent=`${pct}%`;confidenceFillEl.style.width=`${pct}%`;lineGridEl.innerHTML="";(data.lines||[]).forEach((line,i)=>{const el=document.createElement("div");el.className="char-chip";el.innerHTML=`<span class="char-symbol">Line ${i+1}: ${escapeHtml(line.text)}</span><span class="char-badge badge-high">${Math.round(line.confidence*100)}%</span>`;lineGridEl.appendChild(el)});if(!(data.lines||[]).length)lineGridEl.innerHTML="<p class='no-chars'>No readable handwritten text detected.</p>";drawBoundingBoxes(data.lines||[]);copyBtn.hidden=!data.text}catch(e){loadingState.hidden=true;errorTextEl.textContent=`Error: ${e.message}`;errorTextEl.hidden=false}finally{recognizeBtn.disabled=false}});
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
copyBtn.addEventListener("click",()=>{navigator.clipboard.writeText(recognizedTextEl.textContent).then(()=>{const old=copyBtn.innerHTML;copyBtn.innerHTML="✓ Copied!";setTimeout(()=>copyBtn.innerHTML=old,1500)})});
resetBtn.addEventListener("click",()=>{selectedFile=null;fileInput.value="";imageWrapper.hidden=true;previewImg.src="";clearOverlayCanvas();dropPrompt.hidden=false;recognizeBtn.disabled=true;resetBtn.hidden=true;resultsCard.hidden=true});
